# Generated by Django 4.2.21 on 2025-09-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(choices=[('gas', 'Gas'), ('temperature', 'Temperature')], max_length=20)),
                ('value', models.FloatField()),
                ('status', models.CharField(choices=[('normal', 'Normal'), ('warning', 'Warning'), ('danger', 'Danger')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=20, unique=True)),
                ('warning_min', models.FloatField(default=0)),
                ('warning_max', models.FloatField(default=100)),
                ('danger_min', models.FloatField(default=0)),
                ('danger_max', models.FloatField(default=200)),
            ],
        ),
    ]
